### ISSUE TITLE
iOS 10 Compatibility

### ISSUE THREAD

**Issue by karnakar** [MarioIannotta/SwiftyContextMenu#1]
Hi,

It is a well written library going through underlying concepts, seems there is compatibility issue in iOS 10. Please check attached screenshot. On top left button action menu is not popping up.
For bottom button it's working.

![Simulator Screen Shot - iPhone 6S - 2020-06-19 at 12 21 52](https://user-images.githubusercontent.com/5584919/85105389-18a31b80-b228-11ea-8e53-c928d4b00bb5.png)

**Comment by MarioIannotta** [comment]
Whoops, I have the fix ready, I'll publish a new release today.
Thanks for the feedback!

**Comment by MarioIannotta** [comment]
This issue has been fixed in https://github.com/MarioIannotta/SwiftyContextMenu/commit/3bc813c4dec133e78232339de74bdc8a7fc6e004 and released in [0.1.2](https://github.com/MarioIannotta/SwiftyContextMenu/releases/tag/0.1.2).
