### ISSUE TITLE
Position Changed

### ISSUE THREAD

**Issue by syedrazackimran** [MarioIannotta/SwiftyContextMenu#6]
Hi, 

Thanks for your work. 

I am facing some position change issues, I added **SwityContextMenu** in collectionViewCell. When i tapped the cell. X position moved. Here i added some screenshots check it once. I added UIContext ScreenShot Also Check it once.

//Below Screen I Used **SwiftyContextMenu**.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-13 at 17 32 07](https://user-images.githubusercontent.com/15051045/90132319-33f35880-dd8b-11ea-8d7c-b8ba121cb2d5.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-13 at 17 32 10](https://user-images.githubusercontent.com/15051045/90132334-3950a300-dd8b-11ea-990f-040dc6cb72e5.png)

// Belongs to **UIContextMenu**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-13 at 17 11 37](https://user-images.githubusercontent.com/15051045/90132414-6b620500-dd8b-11ea-9fda-22294860ffcc.png)

Kindly do needfully. Thanks.

**Comment by MarioIannotta** [comment]
I think you should 
- decrease the `padding` parameter of the provided [Layout](https://github.com/MarioIannotta/SwiftyContextMenu/blob/78b8335f57a5bb598b2ce8822c0b6562571c3f32/SwiftyContextMenu/ContextMenu.swift#L69) struct.
- set the upper bound of `sourceViewBounceRange` parameter of the provided [ContextMenuAnimation](https://github.com/MarioIannotta/SwiftyContextMenu/blob/78b8335f57a5bb598b2ce8822c0b6562571c3f32/SwiftyContextMenu/ContextMenu.swift#L56) struct to `1`.

Let me know if this helps.

**Comment by syedrazackimran** [comment]
> I think you should
> 
> * decrease the `padding` parameter of the provided [Layout](https://github.com/MarioIannotta/SwiftyContextMenu/blob/78b8335f57a5bb598b2ce8822c0b6562571c3f32/SwiftyContextMenu/ContextMenu.swift#L69) struct.
> * set the upper bound of `sourceViewBounceRange` parameter of the provided [ContextMenuAnimation](https://github.com/MarioIannotta/SwiftyContextMenu/blob/78b8335f57a5bb598b2ce8822c0b6562571c3f32/SwiftyContextMenu/ContextMenu.swift#L56) struct to `1`.
> 
> Let me know if this helps.

Hi, Thanks for your reply.

```
        let layout = ContextMenuLayout(width: 250, spacing: 20, padding: 0, sourceViewCornerRadius: 0)
        let animation = ContextMenuAnimation(sourceViewBounceRange: 0.9...1.0)
        let contextMenu = ContextMenu(title: nil, actions: actions, layout: layout, animation: animation, delegate: self)

```
Now it's fine thanks for your support, **I'll Close this issues**.  I'll recommended make animation similar like **UIContextMenu**
